Repository ROCm/ROCm, pull requests merged in 2024-01, with the labels that each got.

#2780 Mi300 info update
  CHANGELOG.md
  tools/autotag/templates/rocm_changes/6.0.0.md
Labels: Documentation

#2775 docs(gpu-enabled-mpi.rst): Fix links to 3rd party support matrices
  docs/conceptual/cmake-packages.rst
  docs/how-to/gpu-enabled-mpi.rst
Labels: Documentation

#2819 corrections for Issue #2753
  docs/conceptual/gpu-memory.md
Labels: Documentation

#2816 docs(versions.md): Add 5.6.1 to versions list
  docs/release/versions.md
Labels: Documentation

#2824 docs(versions.md): Add 5.6.1 to versions list
  docs/release/versions.md
Labels: Documentation, 6.0.0

#2826 docs(versions.md): Add 5.6.1 to versions list
  docs/release/versions.md
Labels: Documentation, 5.7.0

#2825 docs(versions.md): Add 5.6.1 to versions list
  docs/release/versions.md
Labels: Documentation, 5.7.1
