Repository ROCm/ROCm, pull requests merged in 2024-05, with the labels that each got.

#3095 update for swdev-459863
  .wordlist.txt
  docs/conceptual/compiler-topics.md
  docs/conceptual/using-gpu-sanitizer.md
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation, 6.1.0

#3101 Update manifest to 6.1.1
  default.xml
Labels: 6.1.1

#3113 updates for SWDEV-459863
  .wordlist.txt
  docs/conceptual/compiler-topics.md
  docs/conceptual/using-gpu-sanitizer.md
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation, 6.1.0, 6.1.1

#3114 cherry-pick Docs/6.1.1
  .wordlist.txt
  docs/conceptual/compiler-topics.md
  docs/conceptual/using-gpu-sanitizer.md
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation, 6.1.1

#3118 Merge develop into roc-6.1.x
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/tag-builds/AMDMIGraphX.yml
  .azuredevops/tag-builds/hipfort.yml
  .azuredevops/tag-builds/rocSOLVER.yml
  .azuredevops/tag-builds/rocWMMA.yml
  .wordlist.txt
  CHANGELOG.md
  RELEASE.md
  docs/conceptual/compiler-topics.md
  docs/conceptual/using-gpu-sanitizer.md
  docs/index.md
  docs/sphinx/_toc.yml.in
  tools/autotag/templates/rocm_changes/6.1.1.md
Labels: 6.1.1

#3183 docs(conf.py): Update PDF version to 6.1.1
  docs/conf.py
Labels: 6.1.1

#3181 docs(conf.py): Update PDF version to 6.0.2
  docs/conf.py
Labels: 6.0.2

#3182 docs(conf.py): Update PDF version to 6.1.0
  docs/conf.py
Labels: 6.1.0

#3179 Update documentation requirements for docs/6.1.0 branch
  docs/conf.py
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: 6.1.0

#3190 hipcc doc link
  docs/what-is-rocm.rst
Labels: Documentation

#3204 hipFFT External CI: Missing vmImage syntax for base pool
  .azuredevops/components/hipFFT.yml
Labels: External CI

#3206 External CI: updated cmake dependencies
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/templates/steps/dependencies-cmake-latest.yml
Labels: External CI

#3203 MIOpen External CI: Add rocprofiler-register dependency
  .azuredevops/components/MIOpen.yml
Labels: External CI

#3209 External CI: Dockerless + latest source for rocprofiler and rocm_bandwidth_test
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocprofiler.yml
Labels: External CI

#3211 External CI: Remove redundant rocm_smi_lib pipeline ID
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI
