Repository ROCm/ROCm, pull requests merged in 2024-11, with the labels that each got.

#3982 External CI: add roctracer to rocBLAS deps
  .azuredevops/components/rocBLAS.yml
Labels: External CI

#3983 External CI: decode test changes
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/templates/steps/dependencies-other.yml
Labels: External CI

#3992 Add Omniperf changelog to 6.2.1 release notes and fix RDC version in compat matrix
  RELEASE.md
  docs/compatibility/compatibility-matrix-historical-6.0.csv
  docs/compatibility/compatibility-matrix.rst
Labels: 6.2.1

#3996 External CI: add aomp as rocprofiler-systems dependency
  .azuredevops/components/rocprofiler-systems.yml
Labels: External CI

#3994 Fix RDC version string in compat matrix and 6.2.2 release notes
  RELEASE.md
  docs/compatibility/compatibility-matrix-historical-6.0.csv
  docs/compatibility/compatibility-matrix.rst
Labels: 6.2.2

#4000 External CI: remove omniperf from nightly
  .azuredevops/nightly/rocm-nightly.yml
Labels: External CI

#3993 External CI: allow test failures to present as failures on Github
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/omnitrace.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocprofiler-compute.yml
  .azuredevops/components/rocprofiler-systems.yml
  .azuredevops/components/rpp.yml
  .azuredevops/templates/steps/test.yml
Labels: External CI

#4016 External CI: disable rdmatest and rocrtstFunc.Memory_Max_Mem
  .azuredevops/components/ROCR-Runtime.yml
Labels: External CI

#4025 External CI: fix comgr build
  .azuredevops/components/llvm-project.yml
Labels: External CI

#4027 External CI: increase Tensile test timeout to 90 mins
  .azuredevops/components/Tensile.yml
Labels: External CI

#4031 Change How to ToC and index
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation

#4050 External CI: use MIOpen's requirements.txt
  .azuredevops/components/MIOpen.yml
  .azuredevops/templates/steps/miopen-get-ck-build.yml
Labels: External CI

#4052 External CI: add ROCM_PATH to rocprofiler-systems/compute
  .azuredevops/components/rocprofiler-compute.yml
  .azuredevops/components/rocprofiler-systems.yml
Labels: External CI

#4057 External CI: rocprofiler-compute test fixes
  .azuredevops/components/rocprofiler-compute.yml
Labels: External CI

#4058 External CI: ROCR build release, hipBLAS test fix
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/hipBLAS.yml
Labels: External CI

#4060 External CI: set MIOpen dependencies install path
  .azuredevops/components/MIOpen.yml
Labels: External CI
