Repository ROCm/ROCm, pull requests merged in 2024-10, with the labels that each got.

#3763 Add links to gpu cluster network guides
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation

#3852 External CI: Fix rocPyDecode wheel creation
  .azuredevops/components/rocPyDecode.yml
Labels: External CI

#3689 External CI: Add option to pull mainline branch for dependencies
  .azuredevops/ci-builds/aomp-mainline.yml
  .azuredevops/ci-builds/aomp-staging.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3864 External CI: add a global variable to control gfx942 tests
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCgdb.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/omniperf.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/rocr_debug_agent.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3871 External CI: update component default/mainline branches
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3872 External CI: Stop building gfx90a
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/hipBLAS-common.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/omniperf.yml
  .azuredevops/components/omnitrace.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocprofiler-sdk.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
  .azuredevops/dependencies/grpc.yml
  .azuredevops/dependencies/gtest.yml
  .azuredevops/dependencies/lapack.yml
  .azuredevops/nightly/pytorch.yml
  .azuredevops/nightly/rocm-nightly.yml
Labels: External CI

#3873 Add building doc section
  docs/contribute/building.md
  docs/data/contribute/commit-status.png
  docs/sphinx/_toc.yml.in
Labels: 6.2.2

#3876 External CI: programmatically get latest aqlprofile
  .azuredevops/templates/steps/dependencies-aqlprofile.yml
Labels: External CI

#3877 External CI: use ctest for rocm-examples
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#3884 External CI: Tensile pipeline
  .azuredevops/components/Tensile.yml
  .azuredevops/tag-builds/Tensile.yml
Labels: External CI

#3885 Add oversubscription conceptual doc
  .wordlist.txt
  docs/conceptual/oversubscription.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation

#3896 External CI: Add pipeline to build upstream boost
  .azuredevops/dependencies/boost.yml
  .azuredevops/tag-builds/boost.yml
  .azuredevops/templates/steps/dependencies-boost.yml
  .azuredevops/variables-global.yml
Labels: External CI

#3898 Update bitsandbytes default branch in docs
  docs/how-to/llm-fine-tuning-optimization/model-quantization.rst
  docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst
Labels: Documentation

#3900 [docs/6.2.2] Update bitsandbytes branch in docs (#3898)
  docs/how-to/llm-fine-tuning-optimization/model-quantization.rst
  docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst
Labels: Documentation, 6.2.2

#3891 Cherry pick to docs/6.2.2: Add building doc section (#3873)
  docs/contribute/building.md
  docs/data/contribute/commit-status.png
  docs/sphinx/_toc.yml.in
Labels: 6.2.2

#3890 Cherry pick to roc-6.2.x: Add building doc section (#3873)
  docs/contribute/building.md
  docs/data/contribute/commit-status.png
  docs/sphinx/_toc.yml.in
Labels: ROCm 6.2.0

#3901 Update bitsandbytes branch in docs (#3898)
  docs/how-to/llm-fine-tuning-optimization/model-quantization.rst
  docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst
Labels: Documentation, ROCm 6.2.0

#3903 External CI: use Boost template for MIOpen
  .azuredevops/components/MIOpen.yml
  .azuredevops/templates/steps/dependencies-boost.yml
Labels: External CI

#3906 External CI: create rocprofiler-systems pipeline
  .azuredevops/components/rocprofiler-systems.yml
  .azuredevops/tag-builds/rocprofiler-systems.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3908 External CI: omnitrace/rocprof-sys pipeline IDs
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#3915 External CI: Change when snap installs cmake on test system
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3920 docs: Remove invalid amd_iommu=on parameter (#3919)
  docs/how-to/system-optimization/mi100.md
  docs/how-to/system-optimization/mi200.md
  docs/how-to/system-optimization/mi300x.rst
  docs/how-to/system-optimization/w6000-v620.md
  tools/autotag/templates/highlights/5.3.0.md
Labels: Documentation, ROCm 6.2.0

#3921 docs: Remove invalid amd_iommu=on parameter
  docs/how-to/system-optimization/mi100.md
  docs/how-to/system-optimization/mi200.md
  docs/how-to/system-optimization/mi300x.rst
  docs/how-to/system-optimization/w6000-v620.md
  tools/autotag/templates/highlights/5.3.0.md
Labels: Documentation, 6.2.2

#3922 docs: Remove invalid amd_iommu=on parameter
  docs/how-to/system-optimization/mi100.md
  docs/how-to/system-optimization/mi200.md
  docs/how-to/system-optimization/mi300x.rst
  docs/how-to/system-optimization/w6000-v620.md
  tools/autotag/templates/highlights/5.3.0.md
Labels: Documentation, 6.2.1

#3926 External CI: hipBLASLt build now requires python packaging module
  .azuredevops/components/hipBLASLt.yml
Labels: External CI

#3930 External CI: Moved location of upstream pytorch build scripts
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3931 External CI: disable rocMLIR tests
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/roctracer.yml
Labels: External CI

#3932 External CI: create a GPU diagnostics template
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCgdb.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/Tensile.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/omniperf.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/rocr_debug_agent.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
  .azuredevops/templates/steps/gpu-diagnostics.yml
Labels: External CI

#3934 External CI: Add CK into pytorch build environment
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3938 External CI: add support to disable individual component tests
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCgdb.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/Tensile.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/omniperf.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/rocr_debug_agent.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3939 External CI: AMDMIGraphX greater-equal pip dependencies
  .azuredevops/components/AMDMIGraphX.yml
Labels: External CI

#3940 External CI: rocDecode add libva-amdgpu-dev dependency
  .azuredevops/components/rocDecode.yml
Labels: External CI

#3942 External CI: enumerate GPUs in gpu-diagnostics
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/templates/steps/gpu-diagnostics.yml
Labels: External CI

#3943 External CI: move gpu-diagnostics directly before tests
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCgdb.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/Tensile.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/omniperf.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/rocr_debug_agent.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
Labels: External CI

#3944 External CI: fix HIP_PIPELINE_ID
  .azuredevops/components/copyHIP.yml
Labels: External CI

#3948 External CI: pytorch pipeline updates
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3955 External CI: do not assume python is python3 for rocpydecode
  .azuredevops/components/rocPyDecode.yml
Labels: External CI

#3961 External CI: Add aqlprofile to Tensile test dependencies
  .azuredevops/components/Tensile.yml
Labels: External CI

#3965 Add vllm performance validation doc (6.2.0 version)r
  .wordlist.txt
  docs/conf.py
  docs/how-to/performance-validation/mi300x/vllm-benchmark.rst
  docs/how-to/tuning-guides/mi300x/index.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: 6.2.0

#3967 add vllm performance validation doc (#3964)
  .wordlist.txt
  docs/conf.py
  docs/how-to/performance-validation/mi300x/vllm-benchmark.rst
  docs/how-to/tuning-guides/mi300x/index.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: 6.2.1

#3966 add vllm performance validation doc (#3964)
  .wordlist.txt
  docs/conf.py
  docs/how-to/performance-validation/mi300x/vllm-benchmark.rst
  docs/how-to/tuning-guides/mi300x/index.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: 6.2.2

#3970 External CI: move allowPartiallySucceededBuilds to library variable
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3972 External CI: suppress GPU diag warnings
  .azuredevops/templates/steps/gpu-diagnostics.yml
Labels: External CI

#3973 External CI: rocprofiler-compute pipeline files
  .azuredevops/components/rocprofiler-compute.yml
  .azuredevops/tag-builds/rocprofiler-compute.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3974 External CI: disable reload AMDGPU
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#3977 Update links to vllm perf validation doc (#3971)
  .wordlist.txt
  docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst
  docs/how-to/rocm-for-ai/deploy-your-model.rst
  docs/how-to/tuning-guides/mi300x/workload.rst
Labels: 6.2.0

#3976 Update links to vllm perf validation doc (#3971)
  .wordlist.txt
  docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst
  docs/how-to/rocm-for-ai/deploy-your-model.rst
  docs/how-to/tuning-guides/mi300x/workload.rst
Labels: 6.2.1

#3975 Update links to vllm perf validation doc (#3971)
  .wordlist.txt
  docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst
  docs/how-to/rocm-for-ai/deploy-your-model.rst
  docs/how-to/tuning-guides/mi300x/workload.rst
Labels: 6.2.2
