Repository ROCm/ROCm, pull requests merged in 2024-06, with the labels that each got.

#3215 External CI: use pipelined rocm-core for rocprofiler
  .azuredevops/components/rocprofiler.yml
Labels: External CI

#3216 External CI: Add rocBLAS dependency to rocSPARSE
  .azuredevops/components/rocSPARSE.yml
Labels: External CI

#3258 Remove branch filter for aomp pipeline trigger
  .azuredevops/ci-builds/aomp.yml
Labels: External CI

#3271 External CI: non-interactive apt upgrades
  .azuredevops/templates/steps/dependencies-other.yml
Labels: External CI

#3264 add quarantine_size_mb
  docs/conceptual/using-gpu-sanitizer.md
Labels: Documentation

#3277 External CI: updated rocr_debug_agent dependencies
  .azuredevops/components/rocr_debug_agent.yml
Labels: External CI

#3274 Fix hipTensor build error on develop branch
  .azuredevops/components/hipTensor.yml
  .azuredevops/templates/steps/build-cmake.yml
Labels: External CI

#3276 External CI: Package rocSPARSE matrices for testers to consume
  .azuredevops/components/rocSPARSE.yml
Labels: External CI

#3278 External CI: updated MIOpen dependencies
  .azuredevops/components/MIOpen.yml
Labels: External CI

#3284 update quarantine
  docs/conceptual/using-gpu-sanitizer.md
Labels: Documentation

#3292 update ASan content
  docs/conceptual/using-gpu-sanitizer.md
Labels: Documentation

#3288 cherry-pick ASan content
  docs/conceptual/using-gpu-sanitizer.md
Labels: Documentation

#3291 cherry-pick PR #3284
  .wordlist.txt
  docs/conceptual/using-gpu-sanitizer.md
Labels: Documentation

#3290 cherry pick PR #3284
  docs/conceptual/using-gpu-sanitizer.md
Labels: Documentation

#3304 External CI: Update aqlprofile binary used for rocprofiler
  .azuredevops/components/rocprofiler.yml
Labels: External CI

#3313 remove nvcc
  CHANGELOG.md
  tools/autotag/templates/rocm_changes/6.0.0.md
Labels: Documentation, 6.0.0

#3324 remove nvcc (#3313)
  CHANGELOG.md
  tools/autotag/templates/rocm_changes/6.0.0.md
Labels: Documentation

#3320 remove nvcc (#3313)
  CHANGELOG.md
  tools/autotag/templates/rocm_changes/6.0.0.md
Labels: Documentation

#3321 remove nvcc (#3313)
  CHANGELOG.md
  tools/autotag/templates/rocm_changes/6.0.0.md
Labels: Documentation

#3322 remove nvcc (#3313)
  CHANGELOG.md
  tools/autotag/templates/rocm_changes/6.0.0.md
Labels: Documentation

#3323 remove nvcc (#3313)
  tools/autotag/templates/rocm_changes/6.0.0.md
Labels: Documentation

#3317 External CI: Latest source pipeline for rocm-examples
  .azuredevops/components/rocm-examples.yml
  .azuredevops/tag-builds/rocm-examples.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3331 External CI: remove redundant rocm-examples build flags
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#3339 license information updated
  LICENSE
  docs/about/license.md
Labels: Documentation

#3342 license information updated (#3339)
  LICENSE
  docs/about/license.md
Labels: Documentation

#3341 license information updated (#3339)
  LICENSE
  docs/about/license.md
Labels: Documentation

#3340 license information updated (#3339)
  LICENSE
  docs/about/license.md
Labels: Documentation

#3348 added ROCm Core and AMD SMI
  docs/about/license.md
Labels: Documentation

#3350 added ROCm Core and AMD SMI (#3348)
  docs/about/license.md
Labels: Documentation

#3349 added ROCm Core and AMD SMI (#3348)
  docs/about/license.md
Labels: Documentation

#3351 added ROCm Core and AMD SMI (#3348)
  docs/about/license.md
Labels: Documentation

#3361 remove Magma
  docs/data/how-to/framework_install_2024_05_23.png
  docs/how-to/deep-learning-rocm.rst
  docs/index.md
Labels: Documentation

#3362 Fix card text color in index
  docs/index.md
Labels: Documentation

#3275 Change composable_kernel CI pipeline to build for all architectures
  .azuredevops/components/composable_kernel.yml
Labels: External CI

#3365 External CI: Add initial support for rocAL
  .azuredevops/components/rocAL.yml
  .azuredevops/tag-builds/rocAL.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/build-cmake.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3373 External CI: Fix a typo from composable_kernel pipeline
  .azuredevops/components/composable_kernel.yml
Labels: External CI
