Repository ROCm/ROCm, pull requests merged in 2024-09, with the labels that each got.

#3673 External CI: fix rocPRIM test artifact download
  .azuredevops/components/rocPRIM.yml
Labels: External CI

#3683 External CI: create symlinks for llvm binaries
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3684 External CI: Add torchvision to nightly pytorch job
  .azuredevops/nightly/pytorch.yml
  .azuredevops/patches/pytorch/0001-ROCm-CI-patches.patch
Labels: External CI

#3685 External CI: rocminfo, skip llvm symlink and publishing tests
  .azuredevops/components/rocminfo.yml
Labels: External CI

#3687 External CI: Leverage aomp build scripts
  .azuredevops/ci-builds/aomp.yml
  .azuredevops/components/aomp.yml
  .azuredevops/tag-builds/aomp.yml
Labels: External CI

#3694 External CI: Bump version string in rocm-core pipeline
  .azuredevops/components/rocm-core.yml
Labels: External CI

#3698 External CI: fix aomp repo variable name
  .azuredevops/ci-builds/aomp.yml
Labels: External CI

#3699 External CI: build shared libs for ROCR-Runtime
  .azuredevops/components/ROCR-Runtime.yml
Labels: External CI

#3702 External CI: Copy aomp artifacts to llvm directory before tarball.
  .azuredevops/components/aomp.yml
Labels: External CI

#3703 External CI: Add gfx942 testing for composable_kernel
  .azuredevops/components/composable_kernel.yml
Labels: External CI

#3706 External CI: Change rccl checkout to recursive submodules
  .azuredevops/components/rccl.yml
Labels: External CI

#3704 External CI: rocAL tests & reload AMDGPU for tests
  .azuredevops/components/rocAL.yml
  .azuredevops/templates/steps/test.yml
Labels: External CI

#3707 External CI: Change HIPIFY pipelines to include testing
  .azuredevops/components/HIPIFY.yml
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3708 External CI: Change Default Behaviour From #3704
  .azuredevops/components/rocAL.yml
  .azuredevops/templates/steps/test.yml
Labels: External CI

#3709 External CI: rccl submodule followup to #3706
  .azuredevops/components/HIPIFY.yml
  .azuredevops/components/rccl.yml
Labels: External CI

#3716 External CI: rccl use latest cmake
  .azuredevops/components/rccl.yml
  .azuredevops/templates/steps/dependencies-cmake-latest.yml
Labels: External CI

#3714 External CI: add cmake to rocm-examples
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#3710 External CI: create AOCL template
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/templates/steps/dependencies-aocl.yml
Labels: External CI

#3717 External CI: Add testing to hipBLASLt and hipSPARSELT pipelines
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipSPARSELt.yml
Labels: External CI

#3720 External CI: Add smoke tests to rocMLIR
  .azuredevops/components/rocMLIR.yml
Labels: External CI

#3721 External CI: rocm-examples tests
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#3725 External CI: half component smoke test
  .azuredevops/components/half.yml
Labels: External CI

#3731 External CI: hipfort smoke tests
  .azuredevops/components/hipfort.yml
Labels: External CI

#3740 External CI: update aqlprofile to 6.2
  .azuredevops/templates/steps/dependencies-aqlprofile.yml
Labels: External CI

#3745 External CI: aomp smoke test
  .azuredevops/ci-builds/aomp.yml
  .azuredevops/components/aomp.yml
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3747 External CI: rccl unit tests
  .azuredevops/components/rccl.yml
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3750 External CI: hip-tests unit tests
  .azuredevops/components/hip-tests.yml
Labels: External CI

#3752 External CI: hipBLASLt roctracer dependency and ccache build
  .azuredevops/components/hipBLASLt.yml
Labels: External CI

#3770 Add 6.2.1 to version list
  docs/release/versions.md
Labels: 6.2.1

#3773 Update 6.2 release notes
  .wordlist.txt
  README.md
  RELEASE.md
  default.xml
  docs/release/versions.md
  tools/autotag/templates/highlights/6.2.1.md
  tools/autotag/templates/known_issues/6.2.1.md
  tools/autotag/templates/support/6.2.1.md
  tools/autotag/templates/upcoming_changes/6.2.1.md
Labels: 6.2.0, 6.2.1

#3774 Update 6.2.1 docs
  .wordlist.txt
  README.md
  RELEASE.md
  default.xml
  docs/release/versions.md
  tools/autotag/templates/highlights/6.2.1.md
  tools/autotag/templates/known_issues/6.2.1.md
  tools/autotag/templates/support/6.2.1.md
  tools/autotag/templates/upcoming_changes/6.2.1.md
Labels: 6.2.1

#3781 External CI: Replace libomp-dev dependencies with aomp
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rpp.yml
Labels: External CI

#3784 External CI: Add rocprofiler v1 and v2 smoke tests
  .azuredevops/components/rocprofiler.yml
Labels: External CI

#3785 External CI: ROCgdb smoke tests
  .azuredevops/components/ROCgdb.yml
  .azuredevops/templates/steps/build-autotools.yml
Labels: External CI

#3786 External CI: rocPyDecode Smoke Test
  .azuredevops/components/rocPyDecode.yml
Labels: External CI

#3788 External CI: omniperf pipeline
  .azuredevops/components/omniperf.yml
  .azuredevops/tag-builds/omniperf.yml
  .azuredevops/templates/steps/dependencies-other.yml
Labels: External CI

#3790 External CI: create omniperf pipeline IDs, update nightly build
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#3796 External CI: Publish wheel as artifact for rocPyDecode
  .azuredevops/components/rocPyDecode.yml
Labels: External CI

#3799 External CI: fix hip-tests symlink creation
  .azuredevops/components/hip-tests.yml
Labels: External CI

#3801 Docs: Add Ubuntu 24.04.1
  RELEASE.md
  docs/compatibility/compatibility-matrix-historical-6.0.csv
  docs/compatibility/compatibility-matrix.rst
  tools/autotag/templates/support/6.2.1.md
Labels: Documentation

#3800 External CI: fixes for rocMLIR and nightly build
  .azuredevops/components/rocMLIR.yml
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#3727 remove llvm-alt license
  docs/about/license.md
Labels: Documentation

#3809 External CI: enable ROCR-Runtime tests
  .azuredevops/components/ROCR-Runtime.yml
Labels: External CI

#3811 External CI: default branches for hip-tests, omniperf
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3812 External CI: omnitrace build pipeline
  .azuredevops/components/omnitrace.yml
  .azuredevops/tag-builds/omnitrace.yml
Labels: External CI

#3814 External CI: AMDMIGraphX Build Fix
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/composable_kernel.yml
Labels: External CI

#3815 External CI: test fixes w/ roctracer, list omniperf as partially succeeding
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3816 External CI: rpp tests
  .azuredevops/components/rpp.yml
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3819 External CI: Build pipeline for rocprofiler-sdk
  .azuredevops/components/rocprofiler-sdk.yml
  .azuredevops/tag-builds/rocprofiler-sdk.yml
Labels: External CI

#3818 External CI: Fix/add missing pipeline IDs
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#3822 External CI: omnitrace tests
  .azuredevops/components/omnitrace.yml
Labels: External CI

#3827 Update tags to 6.2.2
  README.md
  default.xml
  tools/autotag/components.xml
Labels: 6.2.2

#3825 External CI: add roctracer to roc/hipSOLVER test deps
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/rocSOLVER.yml
Labels: External CI

#3824 External CI: add rocprofiler-sdk pipeline IDs
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#3837 External CI: MIOpen tests
  .azuredevops/components/MIOpen.yml
Labels: External CI

#3838 External CI: filter out hipTensor extended tests
  .azuredevops/components/hipTensor.yml
Labels: External CI
