Repository ROCm/ROCm, pull requests merged in 2024-08, with the labels that each got.

#3524 External CI: download component staging builds by default
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3527 External CI: change ROCdbgapi default branch
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3544 External CI: Parallel per GPU jobs and file filters
  .azuredevops/components/roctracer.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/artifact-upload.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3545 External CI: Nightly pytorch packaging
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3553 Cherry pick #3541 to roc-6.2.x
  default.xml
Labels: 6.2.0

#3550 External CI: don't set latestFromBranch for tag-builds and fixed dependencies
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3555 External CI: fix ROCgdb component name
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3551 External CI: Parallel per-GPU job support for other components
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/HIP.yml
  .azuredevops/components/HIPIFY.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCdbgapi.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/aomp-extras.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/half.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/llvm-project.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/rocr_debug_agent.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3577 External CI: Adjustments from per-GPU job deployment.
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/hipSPARSELt.yml
Labels: External CI

#3578 External CI: CK set -Wno-missing-include-dirs
  .azuredevops/components/composable_kernel.yml
Labels: External CI

#3586 External CI Pytorch Job Updates
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3584 External CI: add OpenCL ICD libs to HIP/clr
  .azuredevops/components/HIP.yml
Labels: External CI

#3589 External CI: rocDecode dependency update for PR #408
  .azuredevops/components/rocDecode.yml
Labels: External CI

#3588 External CI: Move llvm output folder to expected path (Part 1)
  .azuredevops/components/llvm-project.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3594 Revert "External CI: Move llvm output folder to expected path (Part 1)"
  .azuredevops/components/llvm-project.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3597 Fix for hipother External CI pipeline
  .azuredevops/components/HIP.yml
Labels: External CI

#3593 External CI: fix rocDecode CXX compiler
  .azuredevops/components/rocDecode.yml
Labels: External CI

#3604 External CI: enable clr and rocMLIR latestFromBranch downloads
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3611 External CI: multi-gfx nightly ROCm builds
  .azuredevops/nightly/rocm-nightly.yml
Labels: External CI

#3613 External CI: Add hipBLAS-common to hipBLASLt dependency list
  .azuredevops/components/hipBLASLt.yml
Labels: External CI

#3616 External CI: add hipBLAS-common to MIOpen
  .azuredevops/components/MIOpen.yml
Labels: External CI

#3617 External CI: make llvm-project symlink optional
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3618 External CI: Pipeline dependency adjustments for hipBLAS-common
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#3619 External CI: use root disk for ROCm nightly build
  .azuredevops/nightly/rocm-nightly.yml
Labels: External CI

#3620 External CI: fix HIP pipeline ID for copyHIP
  .azuredevops/components/copyHIP.yml
Labels: External CI

#3609 Add rocPyDecode with other changes
  docs/reference/api-libraries.md
Labels: Documentation

#3626 External CI: Increase CK timeout to 4 hours
  .azuredevops/components/composable_kernel.yml
Labels: External CI

#3630 External CI: add hipBLASLt to MIGraphX and ROCmValidationSuite
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/ROCmValidationSuite.yml
Labels: External CI

#3631 External CI: Support for rocPyDecode
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/tag-builds/rocPyDecode.yml
Labels: External CI

#3632 External: Build Pipeline for hip-tests
  .azuredevops/components/HIP.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/tag-builds/hip-tests.yml
  .azuredevops/templates/steps/build-cmake.yml
Labels: External CI

#3634 External CI: add hipBLASLt + roc/hipFFT to rocm-examples
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#3635 External CI: ROCR-Runtime ROCT-Thunk-Interface Combined
  .azuredevops/components/HIP.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#3639 External CI: Build Fixes for llvm-project and rocBLAS
  .azuredevops/components/llvm-project.yml
  .azuredevops/components/rocBLAS.yml
Labels: External CI

#3641 External CI: remove ROCT from nightly build
  .azuredevops/nightly/rocm-nightly.yml
Labels: External CI

#3642 External CI: change ROCR and rpp default branches
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI

#3473 Adding all pipeline variables from Azure
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/templates/steps/ccache.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#3645 External CI: move rocm-examples to medium build pool
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#3482 External CI: integrate first batch of component tests
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-cmake.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-aqlprofile.yml
  .azuredevops/templates/steps/dependencies-other.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/templates/steps/local-artifact-download.yml
  .azuredevops/templates/steps/test.yml
  .azuredevops/variables-global.yml
Labels: External CI
