Repository ROCm/ROCm, pull requests merged in 2024-12, with the labels that each got.

#4075 External CI: install jq in manifest template
  .azuredevops/templates/steps/manifest.yml
Labels: External CI

#4076 External CI: AOMP rename flang/llvm-legacy to flang/llvm-classic
  .azuredevops/components/aomp.yml
Labels: External CI

#4077 External CI: AOMP symlink fix and manifest additions
  .azuredevops/components/aomp.yml
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/manifest.yml
Labels: External CI

#4096 External CI: remove omniperf files again
  .azuredevops/components/omniperf.yml
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/tag-builds/omniperf.yml
Labels: External CI

#4099 Update license.md
  docs/about/license.md
Labels: Documentation, 6.3.0

#4097 Add minor stylistic updates in release notes
  .wordlist.txt
  RELEASE.md
  tools/autotag/templates/highlights/6.3.0.md
  tools/autotag/templates/known_issues/6.3.0.md
  tools/autotag/templates/upcoming_changes/6.3.0.md
Labels: Documentation, 6.3.0

#4100 External CI: give manifest files same naming scheme as build artifacts
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/HIP.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/omnitrace.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocprofiler-compute.yml
  .azuredevops/components/rocprofiler-sdk.yml
  .azuredevops/components/rocprofiler-systems.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
  .azuredevops/templates/steps/manifest.yml
Labels: External CI

#4101 Update license.md
  docs/about/license.md
Labels: Documentation, 6.3.0

#4102 Update license.md
  docs/about/license.md
Labels: Documentation, 6.2.4

#4117 External CI: create pipeline files for rocJPEG
  .azuredevops/components/rocJPEG.yml
  .azuredevops/tag-builds/rocJPEG.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/variables-global.yml
Labels: External CI

#4125 External CI: finalize rocJPEG enablement
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#4127 Update RELEASE.md
  RELEASE.md
Labels: Documentation, 6.3.0

#4141 Revert "Update RELEASE.md"
  RELEASE.md
Labels: Documentation, 6.3.0

#4144 Update index.md
  docs/index.md
Labels: Documentation, 6.3.0

#4146 Update index.md (#4144)
  docs/index.md
Labels: Documentation

#4148 External CI: MIOpen Test Parameters
  .azuredevops/components/MIOpen.yml
Labels: External CI

#4153 External CI: HIP shared library symlinks for rocPyDecode
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#4154 External CI: llvm project comgr disable spirv
  .azuredevops/components/llvm-project.yml
Labels: External CI

#4157 External CI: Typo in rocPyDecode Pipeline Parameter
  .azuredevops/components/rocPyDecode.yml
Labels: External CI

#4166 External CI: Disable rocprof-system openmp target example
  .azuredevops/components/rocprofiler-systems.yml
Labels: External CI

#4051 Revamped PCIe into new format and incorporated style guide
  .wordlist.txt
  docs/conceptual/More-about-how-ROCm-uses-PCIe-Atomics.rst
  docs/conceptual/pcie-atomics.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation

#4173 External CI: Add toggle for torchvision build and test
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#4176 External CI: Add rocprof-sdk and aqlprofile dependencies to rocprof-sys
  .azuredevops/components/rocprofiler-systems.yml
Labels: External CI

#4168 Bar memory update develop
  docs/how-to/Bar-Memory.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation

#4191 External CI: revert sync changes
  .azuredevops/components/omniperf.yml
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/tag-builds/omniperf.yml
  .azuredevops/templates/steps/artifact-download.yml
Labels: External CI
