Repository ROCm/ROCm, pull requests merged in 2025-05, with the labels that each got.

#4706 Link to 6.4.0 RN updated in Changelog.md
  CHANGELOG.md
Labels: Documentation

#4704 Add MPT-30B + LLM Foundry doc
  .wordlist.txt
  docs/conf.py
  docs/how-to/rocm-for-ai/training/benchmark-docker/mpt-llm-foundry.rst
  docs/sphinx/_toc.yml.in
Labels: Documentation

#4699 Ex CI: disable rocm-examples rocfft_callback test
  .azuredevops/components/rocm-examples.yml
Labels: External CI

#4719 rocSHMEM component added to ROCm 6.4.0 documentation
  CHANGELOG.md
  RELEASE.md
  docs/about/license.md
  docs/compatibility/compatibility-matrix-historical-6.0.csv
  docs/compatibility/compatibility-matrix.rst
  docs/data/rocm-software-stack-6_4_0.jpg
  docs/reference/api-libraries.md
  docs/what-is-rocm.rst
Labels: Documentation

#4720 rocSHMEM component added to ROCm 6.4.0 documentation (#4719)
  CHANGELOG.md
  RELEASE.md
  docs/about/license.md
  docs/compatibility/compatibility-matrix-historical-6.0.csv
  docs/compatibility/compatibility-matrix.rst
  docs/data/rocm-software-stack-6_4_0.jpg
  docs/reference/api-libraries.md
  docs/what-is-rocm.rst
Labels: Documentation

#4723 Fix incorrect throughput benchmark command in inference/vllm-benchmark.rst
  docs/how-to/rocm-for-ai/inference/index.rst
  docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
Labels: Documentation

#4724 [docs/6.4.0] Fix incorrect throughput benchmark command in inference/vllm-benchmar…
  docs/how-to/rocm-for-ai/inference/index.rst
  docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
Labels: Documentation

#4718 Ex CI: add AOMP to RVS
  .azuredevops/components/ROCmValidationSuite.yml
Labels: External CI

#4715 Ex CI: separate ROCgdb build and test jobs
  .azuredevops/components/ROCgdb.yml
Labels: External CI

#4734 Ex CI: remove firstRenderDeviceAccess demand from all components
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocJPEG.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocprofiler-systems.yml
Labels: External CI

#4701 Ex CI: add sparse option to checkout template
  .azuredevops/templates/steps/build-cmake.yml
  .azuredevops/templates/steps/checkout.yml
Labels: External CI

#4736 docs: Add system health check doc under ROCm for AI
  .wordlist.txt
  docs/conf.py
  docs/how-to/rocm-for-ai/inference/pytorch-inference-benchmark.rst
  docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
  docs/how-to/rocm-for-ai/install.rst
  docs/how-to/rocm-for-ai/system-health-check.rst
  docs/how-to/rocm-for-ai/training/benchmark-docker/jax-maxtext.rst
  docs/how-to/rocm-for-ai/training/benchmark-docker/megatron-lm.rst
  docs/how-to/rocm-for-ai/training/benchmark-docker/mpt-llm-foundry.rst
  docs/how-to/rocm-for-ai/training/benchmark-docker/pytorch-training.rst
  docs/how-to/rocm-for-ai/training/index.rst
  docs/how-to/rocm-for-ai/training/prerequisite-system-validation.rst
  docs/sphinx/_toc.yml.in
Labels: Documentation

#4735 Ex CI: skip docker creation on gfx942
  .azuredevops/templates/steps/docker-container.yml
Labels: External CI

#4738 Ex CI: set cmakeSourceDir for all components that set cmakeBuildDir
  .azuredevops/components/HIP.yml
  .azuredevops/components/HIPIFY.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/llvm-project.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/dependencies/grpc.yml
  .azuredevops/dependencies/gtest.yml
Labels: External CI

#4741 Ex CI: set absolute cmakeSourceDir paths
  .azuredevops/components/HIP.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/llvm-project.yml
Labels: External CI

#4743 Ex CI: enable rocPRIM sparse checkout
  .azuredevops/components/rocPRIM.yml
  .azuredevops/templates/steps/checkout.yml
Labels: External CI

#4745 Update RELEASE.md
  RELEASE.md
Labels: Documentation, 6.3.1

#4744 Update RELEASE.md
  RELEASE.md
Labels: Documentation, 6.3.0

#4775 Fix 9070 XT gfx target in gpu-arch-specs table
  CHANGELOG.md
  docs/reference/gpu-arch-specs.rst
Labels: Documentation

#4781 Ex CI: use clr amd-mainline temporarily
  .azuredevops/templates/steps/dependencies-rocm.yml
Labels: External CI

#4820 Add RDNA4 RX 9070 GRE to gpu-arch-specs.rst and RELEASE.md
  RELEASE.md
  docs/reference/gpu-arch-specs.rst
Labels: Documentation

#4835 Ex CI: start creating a unified mathlib build
  .azuredevops/ci-builds/mathlibs-trigger.yml
  .azuredevops/ci-builds/mathlibs.yml
  .azuredevops/components/hipBLAS-common.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocThrust.yml
Labels: External CI

#4836 Add Falcon-180B to vLLM benchmark Docker doc
  docs/data/how-to/rocm-for-ai/inference/vllm-benchmark-models.yaml
Labels: Documentation

#4841 Update ML framework Docker inventories for 6.4.1
  docs/compatibility/ml-compatibility/jax-compatibility.rst
  docs/compatibility/ml-compatibility/pytorch-compatibility.rst
  docs/compatibility/ml-compatibility/tensorflow-compatibility.rst
Labels: Documentation

#4842 Ex CI: make miopen-get-ck-build only fetch from successful CK builds
  .azuredevops/templates/steps/miopen-get-ck-build.yml
Labels: External CI

#4849 [External CI] AlmaLinux8 job for llvm-project
  .azuredevops/components/llvm-project.yml
  .azuredevops/templates/steps/dependencies-dnf.yml
Labels: External CI

#4843 Ex CI: add rocm-cmake to hipBLASLt
  .azuredevops/components/hipBLASLt.yml
Labels: External CI

#4839 Add RHEL 9.6 to compat matrix
  docs/compatibility/compatibility-matrix-historical-6.0.csv
  docs/compatibility/compatibility-matrix.rst
Labels: Documentation

#4855 [External CI] AlmaLinux 8 job for clr and rocminfo
  .azuredevops/components/HIP.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/templates/steps/dependencies-dnf.yml
Labels: External CI

#4857 [External CI] clr/hip workaround
  .azuredevops/components/HIP.yml
Labels: External CI

#4862 HIP 7.0 blog
  RELEASE.md
Labels: Documentation
