Repository ROCm/ROCm, pull requests merged in 2025-01, with the labels that each got.

#4214 External CI: add rocprofiler-sdk to RDC
  .azuredevops/components/rdc.yml
Labels: External CI

#4213 External CI: add libdrm-dev package to rocm_smi_lib
  .azuredevops/components/rocm_smi_lib.yml
Labels: External CI

#4218 External CI: small fixes for RCCL, RPP, MIOpen, CK
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rpp.yml
  .azuredevops/templates/steps/miopen-get-ck-build.yml
Labels: External CI

#4230 External CI: finalize TransferBench enablement
  .azuredevops/README.md
  .azuredevops/components/TransferBench.yml
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#4239 AMDSMI Github reference updated in 6.3.0 Release notes (#4237)
  RELEASE.md
Labels: Documentation

#4066 HPC application list updated
  docs/how-to/rocm-for-hpc/index.rst
Labels: Documentation

#4244 HPC application list updated 6.3.0(#4066)
  docs/how-to/rocm-for-hpc/index.rst
Labels: Documentation

#4245 HPC application list updated 6.3.1 (#4066)
  docs/how-to/rocm-for-hpc/index.rst
Labels: Documentation

#4243 HPC application list updated 6.2.4(#4066)
  docs/how-to/rocm-for-hpc/index.rst
Labels: Documentation

#4238 External CI: add missing rocAL functionalities
  .azuredevops/components/rocAL.yml
Labels: External CI

#4246 External CI: add libdrm-dev to RVS, rocWMMA
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/rocWMMA.yml
Labels: External CI

#4255 External CI: upgrade packaging to >=22.0 for hipBLASLt
  .azuredevops/components/hipBLASLt.yml
Labels: External CI

#4251 ROCProfiler-SDK changelog updated in 6.3.1
  RELEASE.md
Labels: Documentation

#3688 Add metadata to docs
  .wordlist.txt
  docs/conceptual/gpu-arch/mi100.md
  docs/conceptual/gpu-arch/mi250.md
  docs/conceptual/gpu-arch/mi300.md
  docs/how-to/system-debugging.md
  docs/how-to/tuning-guides/mi300x/index.rst
  docs/how-to/tuning-guides/mi300x/system.rst
  docs/how-to/tuning-guides/mi300x/workload.rst
  docs/index.md
Labels: Documentation

#4258 External CI: improve manual run workflow & add mainline dependency support
  .azuredevops/components/AMDMIGraphX.yml
  .azuredevops/components/HIP.yml
  .azuredevops/components/MIOpen.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCdbgapi.yml
  .azuredevops/components/ROCgdb.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/Tensile.yml
  .azuredevops/components/TransferBench.yml
  .azuredevops/components/aomp-extras.yml
  .azuredevops/components/aomp.yml
  .azuredevops/components/composable_kernel.yml
  .azuredevops/components/half.yml
  .azuredevops/components/hip-tests.yml
  .azuredevops/components/hipBLAS-common.yml
  .azuredevops/components/hipBLAS.yml
  .azuredevops/components/hipBLASLt.yml
  .azuredevops/components/hipCUB.yml
  .azuredevops/components/hipFFT.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/hipSPARSELt.yml
  .azuredevops/components/hipTensor.yml
  .azuredevops/components/hipfort.yml
  .azuredevops/components/llvm-project.yml
  .azuredevops/components/omnitrace.yml
  .azuredevops/components/rccl.yml
  .azuredevops/components/rdc.yml
  .azuredevops/components/rocAL.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocBLAS.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocFFT.yml
  .azuredevops/components/rocJPEG.yml
  .azuredevops/components/rocMLIR.yml
  .azuredevops/components/rocPRIM.yml
  .azuredevops/components/rocPyDecode.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocSOLVER.yml
  .azuredevops/components/rocSPARSE.yml
  .azuredevops/components/rocThrust.yml
  .azuredevops/components/rocWMMA.yml
  .azuredevops/components/rocm-examples.yml
  .azuredevops/components/rocm_bandwidth_test.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler-compute.yml
  .azuredevops/components/rocprofiler-sdk.yml
  .azuredevops/components/rocprofiler-systems.yml
  .azuredevops/components/rocprofiler.yml
  .azuredevops/components/rocr_debug_agent.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
  .azuredevops/nightly/rocm-nightly.yml
  .azuredevops/templates/steps/artifact-download.yml
  .azuredevops/templates/steps/dependencies-aqlprofile.yml
  .azuredevops/templates/steps/dependencies-rocm.yml
  .azuredevops/variables-global.yml
Labels: External CI

#4260 ROCprofiler SDK changelog added to 6.3.1 RN
  RELEASE.md
Labels: Documentation

#4263 Reference to RDC added in changelog for 631 RN
  RELEASE.md
Labels: Documentation

#4270 External CI: run rocprofiler-sdk tests
  .azuredevops/components/rocprofiler-sdk.yml
  .azuredevops/templates/steps/dependencies-other.yml
  .azuredevops/templates/steps/test.yml
Labels: External CI

#4275 External CI: add rocDecode to rocAL test deps
  .azuredevops/components/rocAL.yml
Labels: External CI

#4280 External CI: add roctracer to hipSPARSELt
  .azuredevops/components/hipSPARSELt.yml
Labels: External CI

#4282 External CI: add rocDecode to rocprofiler-systems
  .azuredevops/components/rocprofiler-systems.yml
Labels: External CI

#4291 External CI: Install pip on LOW_BUILD_POOL pipelines
  .azuredevops/components/HIP.yml
  .azuredevops/components/MIVisionX.yml
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/ROCdbgapi.yml
  .azuredevops/components/ROCmValidationSuite.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/hipRAND.yml
  .azuredevops/components/hipSOLVER.yml
  .azuredevops/components/hipSPARSE.yml
  .azuredevops/components/rocALUTION.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocJPEG.yml
  .azuredevops/components/rocRAND.yml
  .azuredevops/components/rocm-cmake.yml
  .azuredevops/components/rocm-core.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler-register.yml
  .azuredevops/components/rocr_debug_agent.yml
  .azuredevops/components/roctracer.yml
  .azuredevops/components/rpp.yml
Labels: External CI

#4292 External CI: Install cmake on LOW_BUILD_POOL pipelines
  .azuredevops/components/HIP.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/rocm-cmake.yml
  .azuredevops/components/rocm-core.yml
  .azuredevops/components/rocm_smi_lib.yml
  .azuredevops/components/rocminfo.yml
  .azuredevops/components/rocprofiler-register.yml
Labels: External CI

#4290 External CI: Remove aotriton from pytorch build
  .azuredevops/components/ROCR-Runtime.yml
  .azuredevops/components/amdsmi.yml
  .azuredevops/components/rocprofiler-sdk.yml
  .azuredevops/nightly/pytorch.yml
Labels: External CI

#4294 External CI: Docker URL Update
  .azuredevops/templates/steps/docker-container.yml
Labels: External CI

#4299 2nd POC for How to Use ROCm for AI (#282)
  .wordlist.txt
  docs/compatibility/ml-compatibility/pytorch-compatibility.rst
  docs/conf.py
  docs/how-to/deep-learning-rocm.rst
  docs/how-to/llm-fine-tuning-optimization/index.rst
  docs/how-to/rocm-for-ai/fine-tuning/fine-tuning-and-inference.rst
  docs/how-to/rocm-for-ai/fine-tuning/index.rst
  docs/how-to/rocm-for-ai/fine-tuning/multi-gpu-fine-tuning-and-inference.rst
  docs/how-to/rocm-for-ai/fine-tuning/overview.rst
  docs/how-to/rocm-for-ai/fine-tuning/single-gpu-fine-tuning-and-inference.rst
  docs/how-to/rocm-for-ai/index.rst
  docs/how-to/rocm-for-ai/inference-optimization/index.rst
  docs/how-to/rocm-for-ai/inference-optimization/model-acceleration-libraries.rst
  docs/how-to/rocm-for-ai/inference-optimization/model-quantization.rst
  docs/how-to/rocm-for-ai/inference-optimization/optimizing-triton-kernel.rst
  docs/how-to/rocm-for-ai/inference-optimization/optimizing-with-composable-kernel.md
  docs/how-to/rocm-for-ai/inference-optimization/profiling-and-debugging.rst
  docs/how-to/rocm-for-ai/inference-optimization/workload.rst
  docs/how-to/rocm-for-ai/inference/deploy-your-model.rst
  docs/how-to/rocm-for-ai/inference/hugging-face-models.rst
  docs/how-to/rocm-for-ai/inference/index.rst
  docs/how-to/rocm-for-ai/inference/install.rst
  docs/how-to/rocm-for-ai/inference/llm-inference-frameworks.rst
  docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
  docs/how-to/rocm-for-ai/training/index.rst
  docs/how-to/rocm-for-ai/training/scale-model-training.rst
  docs/how-to/rocm-for-ai/training/train-a-model.rst
  docs/how-to/rocm-for-hpc/index.rst
  docs/how-to/system-optimization/index.rst
  docs/how-to/system-optimization/mi100.md
  docs/how-to/system-optimization/mi200.md
  docs/how-to/system-optimization/mi300a.rst
  docs/how-to/system-optimization/mi300x.rst
  docs/how-to/system-optimization/w6000-v620.md
  docs/how-to/tuning-guides/mi300x/index.rst
  docs/how-to/tuning-guides/mi300x/system.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation

#4300 Ex CI: rccl, rocDecode, rocJPEG fixes
  .azuredevops/components/rccl.yml
  .azuredevops/components/rocDecode.yml
  .azuredevops/components/rocJPEG.yml
Labels: External CI

#4283 Fixed link for Llama recipe
  docs/how-to/rocm-for-ai/scale-model-training.rst
Labels: Documentation

#4301 2nd POC for How to Use ROCm for AI 631 (#282)
  .wordlist.txt
  docs/compatibility/ml-compatibility/pytorch-compatibility.rst
  docs/conf.py
  docs/how-to/deep-learning-rocm.rst
  docs/how-to/llm-fine-tuning-optimization/index.rst
  docs/how-to/rocm-for-ai/fine-tuning/fine-tuning-and-inference.rst
  docs/how-to/rocm-for-ai/fine-tuning/index.rst
  docs/how-to/rocm-for-ai/fine-tuning/multi-gpu-fine-tuning-and-inference.rst
  docs/how-to/rocm-for-ai/fine-tuning/overview.rst
  docs/how-to/rocm-for-ai/fine-tuning/single-gpu-fine-tuning-and-inference.rst
  docs/how-to/rocm-for-ai/index.rst
  docs/how-to/rocm-for-ai/inference-optimization/index.rst
  docs/how-to/rocm-for-ai/inference-optimization/model-acceleration-libraries.rst
  docs/how-to/rocm-for-ai/inference-optimization/model-quantization.rst
  docs/how-to/rocm-for-ai/inference-optimization/optimizing-triton-kernel.rst
  docs/how-to/rocm-for-ai/inference-optimization/optimizing-with-composable-kernel.md
  docs/how-to/rocm-for-ai/inference-optimization/profiling-and-debugging.rst
  docs/how-to/rocm-for-ai/inference-optimization/workload.rst
  docs/how-to/rocm-for-ai/inference/deploy-your-model.rst
  docs/how-to/rocm-for-ai/inference/hugging-face-models.rst
  docs/how-to/rocm-for-ai/inference/index.rst
  docs/how-to/rocm-for-ai/inference/install.rst
  docs/how-to/rocm-for-ai/inference/llm-inference-frameworks.rst
  docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
  docs/how-to/rocm-for-ai/training/index.rst
  docs/how-to/rocm-for-ai/training/scale-model-training.rst
  docs/how-to/rocm-for-ai/training/train-a-model.rst
  docs/how-to/rocm-for-hpc/index.rst
  docs/how-to/system-optimization/index.rst
  docs/how-to/system-optimization/mi100.md
  docs/how-to/system-optimization/mi200.md
  docs/how-to/system-optimization/mi300a.rst
  docs/how-to/system-optimization/mi300x.rst
  docs/how-to/system-optimization/w6000-v620.md
  docs/how-to/tuning-guides/mi300x/index.rst
  docs/index.md
  docs/sphinx/_toc.yml.in
Labels: Documentation

#4304 External CI: Docker Environment Creation Apt Fix
  .azuredevops/templates/steps/docker-container.yml
Labels: External CI

#4308 Duplication from GA merge resolved
  RELEASE.md
  docs/conf.py
Labels: Documentation

#4313 Updated ROCm install on Linux installation method link
  docs/how-to/rocm-for-ai/inference-optimization/model-acceleration-libraries.rst
  docs/how-to/rocm-for-ai/inference/install.rst
  docs/how-to/system-optimization/w6000-v620.md
Labels: Documentation

#4324 Broken link fix for 6.3.2
  docs/how-to/rocm-for-ai/inference-optimization/model-acceleration-libraries.rst
  docs/how-to/rocm-for-ai/inference/install.rst
  docs/how-to/system-optimization/w6000-v620.md
Labels: Documentation

#4325 Azure for 631
  docs/data/rocm-software-stack-6_3_2.jpg
  docs/what-is-rocm.rst
Labels: Documentation, 6.3.1
